Data for USA/IN/MARION
Police-Data-Accessibility-Project/Scrapers pull request #45
Opened 2021-04-03 13:07 UTC by EricTurner3

IMPD data for Marion County

2021-04-03 18:12 UTC, richardji7 requested changes
We don't want to keep the data in this repo.  You have leave one as an sample of what it looks like but please remove all other csv from marion/data/impd.

2021-04-04 00:35 UTC, CaptainStabs approved these changes

2021-04-04 03:09 UTC, richardji7 approved these changes

2021-04-04 03:10 UTC, richardji7 commented
Merge Eric Turner's PR.

2021-04-04 03:10 UTC, merged