Adds CFS with bonus repo wide format standardization
Police-Data-Accessibility-Project/Scrapers pull request #67
Opened 2021-04-13 19:15 UTC by CaptainStabs

2021-04-13 19:43 UTC, EricTurner3 submitted a review, later dismissed
Approved:

- I like the PEP8 formatting, Stabs said he used this: https://github.com/psf/black
- Also added antiocha scraper that scrapes PDF files
- There are no terms and conditions on the website so this scraper fits legal requirements

2021-04-13 20:06 UTC, CaptainStabs reviewed
Shouldn't break anything 🤞

2021-04-14 15:56 UTC, EricTurner3 commented on USA/CA/Brea/brea_annual_scraper.py
> +url_2 = "https://www.ci.brea.ca.us/DocumentCenter/View/116/CrimeStats_Brea"
Full Policy found here: https://www.ci.brea.ca.us/DocumentCenter/View/1329/Website-Content-User-Policy

2021-04-14 16:00 UTC, EricTurner3 commented on USA/CA/COL_LosRiosComm/hash.txt
> +50bc9a673d0d3ca790c1e409e3854821
hash is used to verify the data from the last time the script ran is different

2021-04-14 16:02 UTC, EricTurner3 commented on USA/CA/antiocha/antiocha_scraper.py
>  webpage = "https://www.antiochca.gov/police/crime-statistics/crime-statistics/"
searched the site, did not find any terms of service that we would breach

2021-04-14 16:09 UTC, EricTurner3 reviewed
This massive PR entails the following:

- PEP8 format standarization of all files, using the black formatter
- Modifies import statement of `list_pdf_scrapers` module to `base_scrapers`
- new single_pdf_scraper base script & configs
- Modifies import statement of `bs_scrapers` to `common.file_downloaders`
- Uses a variation of single_pdf_scraper to USA/CA/Brea
- new scraper for /USA/CA/antiocha
- modifies import statement of `base_scrapers` to `common` for get_files
- adds a date mechanism to `crimegraphics` scraper to prevent overwrite
- adds new `list_pdf_v3` scraper in `common`
- adds new `single_pdf_scraper` in `common`
- adds `__init__` files for the refactored module directories in `common`
- adds new `downloaders` module in `common\file_downloaders`

Everything looks good, however I am requesting more review on the Legality of /USA/CA/Brea scraper from @josh-chamberlain before approving. Terms of service for their site can be found here: https://www.ci.brea.ca.us/DocumentCenter/View/1329/Website-Content-User-Policy

2021-04-14 16:32 UTC, EricTurner3 requested changes
* Remove the scraper at /USA/CA/Brea pending legal review. It can be added back in another PR.

2021-04-14 16:59 UTC, EricTurner3 approved these changes
- I see several readme's from commits within the past hour
- removed /USA/CA/Brea

2021-04-14 16:59 UTC, merged